### ISSUE TITLE
Links in image captions are each forced to the next line

### ISSUE THREAD

**Issue by desrosj** [richtabor/kanso#18]
On my personal site, I use image captions for image attribution. It seems that the `.wp-image-block a {}` selector is either too broad, or styles for links within `figcaption` need to be added.

At first I though this was a width issue, but it seems that every `<a>` in `.wp-image-block` receives `display: inline-block;`. This creates a really tall caption. This happens for both image and gallery blocks.

![Screenshot 2024-10-21 at 10 12 48 AM](https://github.com/user-attachments/assets/8f6708fe-4991-472f-a164-914dcabe61f4)
![Screenshot 2024-10-21 at 10 13 18 AM](https://github.com/user-attachments/assets/83e6ec15-5166-4b76-aeb6-d1da6e8c47cb)

The screenshots were [taken from this blog post](https://jonathandesrosiers.com/2024/03/wordpress-photo-directory-i-weeks-of-february-11th-february-18th-february-25th-weeks-6-7-8/).

**Comment by richtabor** [comment]
Looks like this is a Gutenberg bug, reported https://github.com/WordPress/gutenberg/issues/67206—and with a fix in the works. Thanks for sharing!
